/**
 * Loads a single event-list node (level/plant/gate/doodad/... or a boss's two-piece zomboss
 * stage) into its mounted EventPieceInfo(s), by resolving its EventResourceDef list and
 * painting each layer (animation / image / composited-image) into the node's DOM element.
 */
import { PamCanvasPlayer } from '../pam/canvas-player';
import { Matrix, degreeToRad } from '../utils/mathTool';
import { MapEventNode, EventPieceInfo, EventResourceDef, WorldMapEventStatus } from '../domain/types';
import { State, imageDimensionsCache } from '../core/state';
import { customEventStatusMap, customCMap, isLastLevelNaturallyClearedGlobal } from '../core/worldMeta';
import { getObjectUrlCached, compileAnimAssets, findFileInGlobal } from '../core/resources';
import { resolveEventResources } from '../events/resolveEventResources';

/**
 * Ensures `item`'s underlying asset is actually decoded/compiled - compileAnimAssets for an
 * animation resource, image decode for an image/composited-image resource - WITHOUT painting
 * anything into the DOM. This is the one place that work happens; loadAnimationToElement and
 * loadImageToElement (the real render-time paint path, below) both call it as their first step,
 * and Start-time preload (preloadAllMapAssets.ts) calls it directly for every resolved event
 * resource. Previously preload only warmed resolveEventResources' structural cache (which file/
 * animData to use) without ever triggering the actual decode - so the first real render of any
 * event node still paid the full compile/decode cost on demand. Sharing this single function
 * between both call sites means there's exactly one implementation of "how to warm this
 * resource" for either path to drift out of sync with.
 */
export async function warmEventResource(item: EventResourceDef): Promise<void> {
  if (item.type === 'animation' && item.animData) {
    await compileAnimAssets(item.animData);
  } else if (item.type === 'image' && item.file) {
    await warmImageDecode(item.file);
  } else if (item.type === 'composited-image' && item.url) {
    await warmImageDecodeByUrl(item.url);
  }
}

export async function warmEventResources(resources: EventResourceDef[]): Promise<void> {
  await Promise.all(resources.map((item) => warmEventResource(item).catch((e) => {
    console.warn('[EventLoader] warmEventResource failed, skipping', e);
  })));
}

/** Decodes `file` exactly once per session (imageDimensionsCache doubles as the "already
 * decoded" marker - the same cache render/PieceLoader.ts's static mapPiece images use, keyed by
 * File identity regardless of what kind of image it is) and records its natural size. Shared by
 * warmEventResource() above and loadImageToElement() below, so a File decoded during preload -
 * or by an earlier use at render time - is never re-decoded from scratch. */
function warmImageDecode(file: File): Promise<{ width: number; height: number }> {
  const cached = imageDimensionsCache.get(file);
  if (cached) return Promise.resolve(cached);
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const dims = { width: img.width, height: img.height };
      imageDimensionsCache.set(file, dims);
      resolve(dims);
    };
    img.onerror = () => resolve({ width: 0, height: 0 });
    img.src = getObjectUrlCached(file);
  });
}

/** url-keyed equivalent of warmImageDecode, for composited-image resources (data: URLs
 * generated by createGeneralGlyphUrl/createKeyGateTextDataUrl) which have no File to key off. */
const compositedImageDimensionsCache = new Map<string, { width: number; height: number }>();
function warmImageDecodeByUrl(url: string): Promise<{ width: number; height: number }> {
  const cached = compositedImageDimensionsCache.get(url);
  if (cached) return Promise.resolve(cached);
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const dims = { width: img.width, height: img.height };
      compositedImageDimensionsCache.set(url, dims);
      resolve(dims);
    };
    img.onerror = () => resolve({ width: 0, height: 0 });
    img.src = url;
  });
}

export function computeEventLocalTransform(node: MapEventNode, extraX = 0, extraY = 0, extraScale = 1): string {
  let m = Matrix.identity;
  const scaleX = (node.m_scaleX ?? 1) * extraScale;
  const scaleY = (node.m_scaleY ?? 1) * extraScale;
  m = Matrix.multiply(m, Matrix.scale(scaleX, scaleY));
  m = Matrix.multiply(m, Matrix.translate(extraX, extraY));
  return `matrix(${m[0]}, ${m[1]}, ${m[2]}, ${m[3]}, ${m[4]}, ${m[5]})`;
}

export async function loadAnimationToElement(
    animData: any,
    parentEl: HTMLDivElement,
    node: MapEventNode,
    options: {
      label: string;
      probabilityBucket?: Record<string, number>;
      probabilitySide?: string;
      delayMin?: number;
      delayMax?: number;
    },
    extraOffset?: { x: number; y: number },
    extraScale?: number
): Promise<PamCanvasPlayer | null> {
  try {
    const assets = await compileAnimAssets(animData);
    if (!assets) return null;

    const { animation, textureMap } = assets;
    const sizeW = animation.size[0] || 400;
    const sizeH = animation.size[1] || 400;

    const el = document.createElement('div');
    el.className = 'map-piece';
    el.style.cssText = `
      left:0px;
      top:0px;
      width:${sizeW}px;
      height:${sizeH}px;
      transform:${computeEventLocalTransform(node, extraOffset?.x ?? 0, extraOffset?.y ?? 0, extraScale)};
    `;
    parentEl.appendChild(el);

    const canvas = document.createElement('canvas');
    canvas.width = sizeW;
    canvas.height = sizeH;
    el.appendChild(canvas);

    const player = new PamCanvasPlayer(canvas, animation, textureMap, animData?.path);
    if (options && options.probabilityBucket) {
      player.setLabelProbabilityBucket(options.probabilityBucket, options.probabilitySide);
    } else if (options && options.label) {
      player.playLabel(options.label);
    }
    if (options && options.delayMin !== undefined && options.delayMax !== undefined) {
      player.setDelayDetails(options.delayMin, options.delayMax);
    }
    State.players.push(player);
    return player;
  } catch (e) {
    console.error('[Event Animation Load Error]', e);
    return null;
  }
}

export function loadImageToElement(
    source: Blob | File | string,
    parentEl: HTMLDivElement,
    node: MapEventNode,
    extraOffset?: { x: number; y: number },
    extraScale?: number,
    flipX?: boolean
): Promise<void> {
  const isFile = source instanceof File || source instanceof Blob;
  const url = isFile ? getObjectUrlCached(source as File) : (source as string);

  const buildElement = (width: number, height: number): void => {
    const el = document.createElement('div');
    el.className = 'map-piece';

    let transformStr = '';
    if (node.m_eventType === 'doodad') {
      const scaleX = node.m_scaleX ?? 1;
      const scaleY = node.m_scaleY ?? 1;
      const angle = degreeToRad(node.m_rotationAngle ?? 0);
      const flipScale = node.m_isArtFlipped ? -1 : 1;

      let m = Matrix.identity;
      m = Matrix.multiply(m, Matrix.scale(scaleX, scaleY));
      m = Matrix.multiply(m, Matrix.translate(0, -height / 2));
      m = Matrix.multiply(m, Matrix.rotate(angle));
      m = Matrix.multiply(m, Matrix.scale(flipScale, 1));
      m = Matrix.multiply(m, Matrix.translate(-width / 2, -height / 2));
      transformStr = `matrix(${m[0]}, ${m[1]}, ${m[2]}, ${m[3]}, ${m[4]}, ${m[5]})`;
    } else {
      let m = Matrix.identity;
      const scaleX = (node.m_scaleX ?? 1) * (extraScale ?? 1);
      const scaleY = (node.m_scaleY ?? 1) * (extraScale ?? 1);
      m = Matrix.multiply(m, Matrix.scale(scaleX, scaleY));
      m = Matrix.multiply(m, Matrix.translate(extraOffset?.x ?? 0, extraOffset?.y ?? 0));

      if (flipX) {
        // 在原矩阵右端依次乘以 scale(-1, 1) 和 translate(-width, 0)
        // 最终得到：基础矩阵 * scale(-1,1) * translate(-width, 0)
        m = Matrix.multiply(m, Matrix.scale(-1, 1));
        m = Matrix.multiply(m, Matrix.translate(-width, 0));
      }
      transformStr = `matrix(${m[0]}, ${m[1]}, ${m[2]}, ${m[3]}, ${m[4]}, ${m[5]})`;
    }

    el.style.cssText = `
      left:0px;
      top:0px;
      width:${width}px;
      height:${height}px;
      background-image:url(${url});
      transform:${transformStr};
    `;
    parentEl.appendChild(el);
  };

  // Fast path: this file/url was already decoded - either by Start-time preload
  // (warmEventResource, above) or an earlier use at render time - so its dimensions are
  // already known and the DOM element can be built immediately, no fresh Image()+onload
  // round-trip needed.
  const cachedDims = isFile
      ? imageDimensionsCache.get(source as File)
      : compositedImageDimensionsCache.get(source as string);
  if (cachedDims) {
    buildElement(cachedDims.width, cachedDims.height);
    return Promise.resolve();
  }

  const warm = isFile ? warmImageDecode(source as File) : warmImageDecodeByUrl(source as string);
  return warm.then((dims) => {
    if (dims.width === 0 && dims.height === 0) return; // decode failed, matches old onerror no-op
    buildElement(dims.width, dims.height);
  });
}

export async function loadResourcesToElement(
    resources: EventResourceDef[],
    element: HTMLDivElement,
    node: MapEventNode,
    players: PamCanvasPlayer[],
    checkInterrupted?: () => boolean
): Promise<boolean> {
  for (const item of resources) {
    if (item.type === 'animation' && item.animData) {
      const player = await loadAnimationToElement(
          item.animData,
          element,
          node,
          item.options || { label: 'idle' },
          item.offset,
          item.scale || 1
      );
      if (checkInterrupted && checkInterrupted()) {
        player?.destroy();
        players.forEach(p => p.destroy());
        return false;
      }
      if (player) players.push(player);
    } else if (item.type === 'composited-image' && item.url) {
      await loadImageToElement(item.url, element, node, item.offset, item.scale || 1);
      if (checkInterrupted && checkInterrupted()) {
        players.forEach(p => p.destroy());
        return false;
      }
    } else if (item.type === 'image' && item.file) {
      await loadImageToElement(item.file, element, node, item.offset, item.scale || 1, item.flipX);
      if (checkInterrupted && checkInterrupted()) {
        players.forEach(p => p.destroy());
        return false;
      }
    }
  }
  return true;
}

/** The absolutely-positioned inner element every event piece hangs its resources off. Pulled
 *  out because loadEventPiecesForNode built this same block 4 times (path_node / zomboss-stage /
 *  zomboss-top / plain node). */
function createVisualWrapper(): HTMLDivElement {
  const wrapper = document.createElement('div');
  wrapper.className = 'event-visual-wrapper';
  wrapper.style.cssText = `
    position: absolute;
    left: 50px;
    top: 50px;
    width: 0px;
    height: 0px;
  `;
  return wrapper;
}

/** Editor-only: double-click a level/boss node to cycle its preview WMED status for testing. */
function toggleNodeStatus(node: MapEventNode): void {
  const currentStatus = customEventStatusMap.get(node.m_eventId) ?? WorldMapEventStatus.locked;
  let nextStatus = WorldMapEventStatus.locked;
  if (currentStatus === WorldMapEventStatus.locked) {
    nextStatus = WorldMapEventStatus.unlocked;
  } else if (currentStatus === WorldMapEventStatus.unlocked) {
    nextStatus = WorldMapEventStatus.cleared;
  } else if (currentStatus === WorldMapEventStatus.cleared) {
    nextStatus = WorldMapEventStatus.locked;
  }
  customEventStatusMap.set(node.m_eventId, nextStatus);

  if (nextStatus !== WorldMapEventStatus.cleared) {
    customCMap.set(node.m_eventId, 0);
  } else {
    // If cleared, default to 1 star (or max stars)
    customCMap.set(node.m_eventId, 1);
  }

  window.dispatchEvent(new CustomEvent('trigger-map-render'));
}

function attachStatusToggle(el: HTMLElement, node: MapEventNode): void {
  el.ondblclick = (e) => {
    e.stopPropagation();
    toggleNodeStatus(node);
  };
}

export async function attachStarsToElement(el: HTMLDivElement, node: MapEventNode): Promise<void> {
  const isLastLevelNaturallyCleared = isLastLevelNaturallyClearedGlobal;

  const getLevelStarLimitAndCountLocal = () => {
    const isChallenge = node.m_isChallengeType === true;

    if (isChallenge) {
      const max_stars = 1;
      const earned_stars = State.data.unlockAll ? 1 : (customCMap.get(node.m_eventId) ?? 0);
      return { max_stars, earned_stars };
    } else {
      if (isLastLevelNaturallyCleared || State.data.unlockAll) {
        const max_stars = 3;
        const earned_stars = State.data.unlockAll ? 3 : (customCMap.get(node.m_eventId) ?? 0);
        return { max_stars, earned_stars };
      } else {
        return { max_stars: 0, earned_stars: 0 };
      }
    }
  };

  const { max_stars, earned_stars } = getLevelStarLimitAndCountLocal();
  if (max_stars <= 0) return;

  // China: images/{res}/UICommon/worldmap/common/star(_empty).png - dynamic resolution per the
  // given spec, unlike international's (pre-existing, left as-is) hardcoded 1536 tier.
  const starFile = State.data.isChinaVersion
      ? findFileInGlobal(`images/${State.data.textureResolution}/UICommon/worldmap/common/star.png`)
      : findFileInGlobal('images/1536/initial/worldmap/common/star.png');
  const starEmptyFile = State.data.isChinaVersion
      ? findFileInGlobal(`images/${State.data.textureResolution}/UICommon/worldmap/common/star_empty.png`)
      : findFileInGlobal('images/1536/initial/worldmap/common/star_empty.png');

  if (!starFile && !starEmptyFile) return;

  const starConfigs: Array<{
    idx: number;
    offsetX: (w: number) => number;
    offsetY: (h: number) => number;
  }> = [];

  if (max_stars === 1) {
    starConfigs.push({
      idx: 1,
      offsetX: (w) => -w / 2,
      offsetY: (h) => -h / 2,
    });
  } else if (max_stars === 3) {
    starConfigs.push({
      idx: 1, // left
      offsetX: (w) => -1.5 * w,
      offsetY: (h) => -h / 2,
    });
    starConfigs.push({
      idx: 2, // mid
      offsetX: (w) => -w / 2,
      offsetY: (h) => -h / 2,
    });
    starConfigs.push({
      idx: 3, // right
      offsetX: (w) => 0.5 * w,
      offsetY: (h) => -h / 2,
    });
  }

  for (const config of starConfigs) {
    const isEarned = config.idx <= earned_stars;
    const fileToUse = isEarned ? starFile : starEmptyFile;
    if (!fileToUse) continue;

    const url = getObjectUrlCached(fileToUse);
    const { width: w, height: h } = await warmImageDecode(fileToUse);
    if (w === 0 && h === 0) continue; // decode failed

    const starEl = document.createElement('div');
    starEl.className = 'map-piece star-icon-piece';

    const oX = config.offsetX(w);
    const oY = config.offsetY(h);

    const transformStr = `matrix(0.65, 0, 0, 0.65, ${0.65 * oX}, ${0.65 * oY + 22 * State.data.textureResolution/600})`;

    starEl.style.cssText = `
      left:0px;
      top:0px;
      width:${w}px;
      height:${h}px;
      background-image:url(${url});
      transform:${transformStr};
      cursor: pointer;
    `;

    starEl.onclick = (e) => {
      e.stopPropagation();
      let newEarned = config.idx;
      if (earned_stars === config.idx) {
        newEarned = config.idx - 1;
      }
      customCMap.set(node.m_eventId, newEarned);

      if (newEarned > 0) {
        customEventStatusMap.set(node.m_eventId, WorldMapEventStatus.cleared);
      }

      window.dispatchEvent(new CustomEvent('trigger-map-render'));
    };

    el.appendChild(starEl);
  }
}

export async function loadEventPiecesForNode(node: MapEventNode): Promise<EventPieceInfo[]> {
  if (node.m_eventType === 'path_node') {
    if (State.data.isLinear) {
      return [];
    }
    const el = document.createElement('div');
    el.className = 'map-piece map-type-event';
    const resolution = State.data.textureResolution;
    el.style.cssText = `
      width:100px;
      height:100px;
      left:${((node.m_position?.x || 0) * resolution) / 600 - 50}px;
      top:${((node.m_position?.y || 0) * resolution) / 600 - 50}px;
    `;

    const visualWrapper = createVisualWrapper();
    el.appendChild(visualWrapper);

    return [{
      node,
      element: el,
      players: [],
      resources: []
    }];
  }

  const resources = await resolveEventResources(node, State.data.selectedWorld || '');
  if (!resources || resources.length === 0) return [];

  const createPieceEl = () => {
    const el = document.createElement('div');
    if (node.m_eventType === 'doodad') {
      el.className = 'map-piece map-type-doodad';
    } else {
      el.className = 'map-piece map-type-event';
    }
    const resolution = State.data.textureResolution;
    el.style.cssText = `
      width:100px;
      height:100px;
      left:${((node.m_position?.x || 0) * resolution) / 600 - 50}px;
      top:${((node.m_position?.y || 0) * resolution) / 600 - 50}px;
    `;
    return el;
  };

  const isBossNode = node.m_eventType === 'level' && node.m_levelNodeType === 'boss';
  const isDanger = node.m_dataString?.endsWith('dangerroom');

  if (isBossNode) {
    const pieces: EventPieceInfo[] = [];

    const stageRes = resources.filter(r => r.type === 'animation' && r.animData?.path.includes('zomboss_node_') && !r.animData.path.includes('hologram'));
    const topRes = resources.filter(r => !(r.type === 'animation' && r.animData?.path.includes('zomboss_node_') && !r.animData.path.includes('hologram')));

    if (stageRes.length > 0) {
      const elStage = createPieceEl();
      const visualWrapper = createVisualWrapper();
      elStage.appendChild(visualWrapper);

      const playersStage: PamCanvasPlayer[] = [];
      await loadResourcesToElement(stageRes, visualWrapper, node, playersStage);
      pieces.push({
        node,
        element: elStage,
        players: playersStage,
        resources: stageRes,
        isZombossStage: true
      });
    }

    if (topRes.length > 0) {
      const elTop = createPieceEl();
      const visualWrapper = createVisualWrapper();
      elTop.appendChild(visualWrapper);

      const playersTop: PamCanvasPlayer[] = [];
      await loadResourcesToElement(topRes, visualWrapper, node, playersTop);

      if (State.data.isLinear === false && !isDanger) {
        await attachStarsToElement(visualWrapper, node);
      }

      attachStatusToggle(elTop, node);

      pieces.push({
        node,
        element: elTop,
        players: playersTop,
        resources: topRes,
        isZombossStage: false
      });
    }

    return pieces;
  } else {
    const el = createPieceEl();
    const visualWrapper = createVisualWrapper();
    el.appendChild(visualWrapper);

    const players: PamCanvasPlayer[] = [];
    await loadResourcesToElement(resources, visualWrapper, node, players);

    const isLevelNode = node.m_eventType === 'level';
    if (isLevelNode && State.data.isLinear === false && !isDanger) {
      await attachStarsToElement(visualWrapper, node);
    }

    if (isLevelNode) {
      attachStatusToggle(el, node);
    }

    return [{
      node,
      element: el,
      players,
      resources
    }];
  }
}
